Repository team-noir/the-pong, pull requests merged in 2023-06, with the labels that each got.

#604 Makefile 리팩토링
  Makefile
Labels: refactoring

#599 환경변수 정리
  .env.development.example
  .env.example
  docker-compose-aws.yml
  docker-compose-dev.yml
  docker-compose.yml
Labels: etc

#605 메인 페이지에 가장 참여자가 많은 순으로 채널 목록 API 호출
  frontend/src/api/rest.v1.ts
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelList.tsx
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/components/organisms/Main.tsx
Labels: feature, 🌝 FE, bonus

#611 메인 페이지에 관전자 순으로 라이브 게임 목록 표시
  frontend/src/api/rest.v1.ts
  frontend/src/components/organisms/Main.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE, bonus

#612 게임 페이지에서 관전자 수 오른쪽 정렬
  frontend/src/components/organisms/Game/index.tsx
Labels: 🌝 FE, etc
