Repository team-noir/the-pong, pull requests merged in 2023-03, with the labels that each got.

#73 라우터 설정
  frontend/.yarn/cache/@remix-run-router-npm-1.3.3-f2831232da-9280f1c3e4.zip
  frontend/.yarn/cache/react-router-dom-npm-6.8.2-9aed31c3b9-eddc8b88e2.zip
  frontend/.yarn/cache/react-router-npm-6.8.2-48f13a628a-9e98d03e1f.zip
  frontend/.yarn/install-state.gz
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/pages/FriendPage.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/OnBoardingPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/Root.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/yarn.lock
Labels: feature, 🌝 FE

#74 Nest.js 초기 프로젝트 설정
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
Labels: feature, 🌚 BE

#76 라우터 테스트 코드 추가
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/tests/App.test.tsx
  frontend/yarn.lock
Labels: 🌝 FE, etc

#78 App import 오류
  frontend/src/index.tsx
Labels: bug, 🌝 FE

#84 프론트엔드 개발 환경 도커 이미지 생성
  README.md
  docker-compose-dev-frontend.yml
  frontend/.dockerignore
  frontend/.yarnrc.yml
  frontend/Dockerfile.dev
Labels: 🌝 FE, etc

#85 prisma 설정
  backend/.env.example
  backend/package.json
  backend/prisma/migrations/20230308051353_thepong_v1/migration.sql
  backend/prisma/migrations/migration_lock.toml
  backend/prisma/schema.prisma
  backend/yarn.lock
  docker-compose.yml
Labels: feature, 🌚 BE

#88 테스트 시 act()로 감싸라는 경고
  frontend/src/tests/App.test.tsx
  frontend/src/tests/Profile.test.tsx
Labels: 🌝 FE, etc

#89 로그인을 할 수 있는 인트로 페이지 구현
  frontend/.pnp.cjs
  frontend/.yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  frontend/.yarn/cache/zustand-npm-4.3.6-c02ac9b7e3-4d3cec0352.zip
  frontend/Dockerfile.dev
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/images/logo_42.svg
  frontend/src/assets/styles/Button.module.css
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/hooks/useStore.ts
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/Root.tsx
  frontend/src/tests/App.test.tsx
  frontend/src/tests/Login.test.tsx
  frontend/src/tests/Profile.test.tsx
  frontend/yarn.lock
Labels: feature, 🌝 FE

#91 자신의 프로필을 수정할 수 있는 프로필 수정 페이지 구현
  frontend/src/assets/styles/FileInputWithImage.module.css
  frontend/src/components/atoms/Label.tsx
  frontend/src/components/atoms/Message.tsx
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/FileInputWithImage.tsx
  frontend/src/components/molecule/TextInputWithMessage.tsx
  frontend/src/components/organisms/Setting.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/tests/App.test.tsx
  frontend/src/tests/Profile.test.tsx
  frontend/src/tests/Setting.test.tsx
Labels: feature, 🌝 FE

#92 프로필 페이지에 친구 추가 버튼 구현
  frontend/src/components/organisms/Profile.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
  frontend/src/tests/__snapshots__/Profile.test.tsx.snap
Labels: feature, 🌝 FE

#93 친구 목록 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/styles/Following.module.css
  frontend/src/components/organisms/Following.tsx
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/FriendPage.tsx
  frontend/src/pages/Root.tsx
  frontend/src/tests/App.test.tsx
  frontend/src/tests/Following.test.tsx
Labels: feature, 🌝 FE

#94 최초 로그인하는 회원에게 보이는 온보딩 플로우 구현
  frontend/src/components/atoms/CheckboxInput.tsx
  frontend/src/components/molecule/CheckboxInputWithLabel.tsx
  frontend/src/components/molecule/FileInputWithImage.tsx
  frontend/src/components/molecule/TextInputWithMessage.tsx
  frontend/src/components/organisms/OnBoarding/MultiSteps.tsx
  frontend/src/components/organisms/OnBoarding/StepAgreements.tsx
  frontend/src/components/organisms/OnBoarding/StepNickname.tsx
  frontend/src/components/organisms/OnBoarding/StepProfileImage.tsx
  frontend/src/components/organisms/OnBoarding/StepWelcome.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/Setting.tsx
  frontend/src/pages/OnBoardingPage.tsx
  frontend/src/tests/OnBoarding.test.tsx
  frontend/src/utils/validatorUtils.ts
Labels: feature, 🌝 FE

#96 회원의 현재 상태를 확인할 수 있는 프로필 사진 옆 아이콘 구현
  frontend/src/assets/styles/Following.module.css
  frontend/src/assets/styles/Profile.module.css
  frontend/src/assets/styles/ProfileImage.module.css
  frontend/src/assets/styles/ProfileImageWithStatus.module.css
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/ProfileImageWithStatus.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/Following/FollowingItem.tsx
  frontend/src/components/organisms/Following/FollowingList.tsx
  frontend/src/components/organisms/Following/index.tsx
  frontend/src/components/organisms/Profile.tsx
  frontend/src/types/userType.ts
Labels: feature, 🌝 FE

#97 회원을 검색할 수 있는 검색바 구현
  frontend/src/App.tsx
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/SearchBar.tsx
  frontend/src/pages/Root.tsx
  frontend/src/pages/SearchResultPage.tsx
Labels: feature, 🌝 FE

#95 회원 프로필 페이지에 차단 버튼 구현
  frontend/src/components/organisms/Profile.tsx
Labels: feature, 🌝 FE

#90 42 OAuth 로그인을 하는 REST API 구현
  .env.example
  backend/.env.example
  backend/package.json
  backend/prisma/migrations/20230313074405_thepong_v1_1/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/prisma/prisma.module.ts
  backend/src/prisma/prisma.service.spec.ts
  backend/src/prisma/prisma.service.ts
  backend/src/users/auth/auth.service.spec.ts
  backend/src/users/auth/auth.service.ts
  backend/src/users/auth/ft.strategy.ts
  backend/src/users/guards/authenticated.guard.ts
  backend/src/users/guards/ft-oauth.guard.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
  backend/yarn.lock
Labels: feature, 🌚 BE

#99 설정 페이지 하위 라우팅 구현
  frontend/src/App.tsx
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/tests/SettingProfile.test.tsx
Labels: feature, 🌝 FE

#100 회원 검색 결과가 표시되는 회원 목록 구현
  frontend/src/assets/styles/SearchResult.module.css
  frontend/src/components/organisms/SearchResult/SearchResultItem.tsx
  frontend/src/components/organisms/SearchResult/SearchResultList.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/pages/SearchResultPage.tsx
Labels: feature, 🌝 FE

#104 메인 페이지에 게임 시작 버튼 & 채널 만들기 버튼 구현
  frontend/src/components/organisms/MainChannels.tsx
  frontend/src/components/organisms/MainGames.tsx
  frontend/src/pages/MainPage.tsx
Labels: feature, 🌝 FE

#103 2FA 설정 페이지 구현
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/tests/Setting2FA.test.tsx
  frontend/src/types/userType.ts
Labels: feature, 🌝 FE

#102 차단 회원 목록 페이지 구현
  frontend/src/assets/styles/Blocks.module.css
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/components/organisms/SettingBlocks/BlocksItem.tsx
  frontend/src/components/organisms/SettingBlocks/BlocksList.tsx
  frontend/src/components/organisms/SettingBlocks/index.tsx
Labels: feature, 🌝 FE

#107 프로필 페이지에서 업적 목록 구현
  frontend/src/assets/styles/Achievement.module.css
  frontend/src/components/organisms/Achievements/AchievementItem.tsx
  frontend/src/components/organisms/Achievements/AchievementList.tsx
  frontend/src/components/organisms/Achievements/index.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Achievements.test.tsx
  frontend/src/tests/Profile.test.tsx
  frontend/src/types/achievementType.ts
Labels: feature, 🌝 FE

#110 회원 목록 컴포넌트 리팩토링
  frontend/src/assets/styles/Following.module.css
  frontend/src/assets/styles/UserItem.module.css
  frontend/src/components/molecule/ProfileImageWithStatus.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/components/molecule/UserList.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/Following/FollowingItem.tsx
  frontend/src/components/organisms/Following/FollowingList.tsx
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/components/organisms/SettingBlocks/BlocksItem.tsx
  frontend/src/components/organisms/SettingBlocks/BlocksList.tsx
  frontend/src/tests/Following.test.tsx
Labels: 🌝 FE, etc

#114 페이지 템플릿 만들기
  frontend/.eslintrc.json
  frontend/src/App.tsx
  frontend/src/assets/styles/AppTemplate.module.css
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/HeaderWithBackButton.tsx
  frontend/src/components/templates/AppTemplate.tsx
  frontend/src/components/templates/AppTemplateWithoutHeader.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/Root.tsx
  frontend/src/pages/Setting2FAPage.tsx
  frontend/src/pages/SettingBlocksPage.tsx
  frontend/src/pages/SettingProfilePage.tsx
  frontend/src/tests/Setting2FA.test.tsx
  frontend/src/tests/SettingProfile.test.tsx
Labels: feature, 🌝 FE

#118 채널 목록 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/styles/Channel.module.css
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelList.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/ChannelNewPage.tsx
  frontend/src/tests/App.test.tsx
  frontend/src/tests/ChannelLobby.test.tsx
  frontend/src/types/channelType.ts
Labels: 🌝 FE, etc

#121 개발용 도커에 Nginx Reverse Proxy 설정
  .env.development.example
  README.md
  backend/src/app.controller.ts
  docker-compose-dev.yml
  frontend/Dockerfile.dev
  nginx/proxy.conf
Labels: 🌚 BE, etc

#124 OAuth redirection 설정
  .env.development.example
  .env.example
  .gitignore
  backend/.dockerignore
  backend/run.sh
  backend/src/users/auth/ft.strategy.ts
  backend/src/users/users.controller.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  docker-compose-dev.yml
Labels: feature, 🌚 BE

#127 로그인을 할 수 있는 인트로 페이지 API 호출
  backend/src/app.controller.ts
  frontend/.pnp.cjs
  frontend/.yarn/cache/@tanstack-query-core-npm-4.26.1-b4ec767cdf-c7bc751d7d.zip
  frontend/.yarn/cache/@tanstack-react-query-npm-4.26.1-1d638817b0-3b43a5acc8.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/tests/Login.test.tsx
  frontend/yarn.lock
Labels: feature, 🌝 FE

#130 nginx dockerfile 추가
  docker-compose-dev.yml
  nginx/Dockerfile
Labels: bug

#149 누락된 nginx dockerfile 반영
  docker-compose-dev.yml
  nginx/Dockerfile
Labels: bug

#129 로그인 상태를 체크하는 REST API 구현
  .env.development.example
  .env.example
  backend/.pnp.cjs
  backend/.yarn/cache/@nestjs-swagger-npm-6.2.1-c0460a6ba1-505d39dcfa.zip
  backend/.yarn/cache/swagger-ui-dist-npm-4.15.5-9e0c8d56dd-b032ecc124.zip
  backend/package.json
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.module.ts
  backend/src/api/auth/auth.service.spec.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/ft.strategy.ts
  backend/src/api/base.document.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.module.ts
  backend/src/api/my/my.service.ts
  backend/src/api/users/users.controller.spec.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.module.ts
  backend/src/api/users/users.service.spec.ts
  backend/src/api/users/users.service.ts
  backend/src/app.module.ts
  backend/src/guards/authenticated.guard.ts
  backend/src/guards/ft-oauth.guard.ts
  backend/src/main.ts
  backend/src/users/guards/authenticated.guard.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  backend/yarn.lock
Labels: feature, 🌚 BE

#151 프로필 요청을 하는 REST API 구현
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.module.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/ft.strategy.ts
  backend/src/api/base.document.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.module.ts
  backend/src/api/my/my.service.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.module.ts
  backend/src/api/users/users.service.ts
  backend/src/app.module.ts
  backend/src/guards/authenticated.guard.ts
  backend/src/main.ts
Labels: feature, 🌚 BE

#154 auth 관련 API 요청 수정
  README.md
  frontend/src/App.tsx
  frontend/src/components/organisms/Login.tsx
Labels: 🌝 FE, etc

#156 axios 사용 & API endpoint 상수로 다루기
  frontend/.pnp.cjs
  frontend/.yarn/cache/axios-npm-1.3.4-01ea685178-7440edefcf.zip
  frontend/.yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  frontend/.yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-ed7fcc2ba0.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Login.tsx
  frontend/src/index.tsx
  frontend/yarn.lock
Labels: feature, 🌝 FE

#160 차단 회원 목록 페이지 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/SettingBlocksPage.tsx
Labels: feature, 🌝 FE

#159 각 회원마다 주어지는 프로필 페이지 API 호출
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#162 userType 재정의
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/components/molecule/UserList.tsx
  frontend/src/components/organisms/ChannelSetting.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/SearchResult/SearchResultItem.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/tests/Achievements.test.tsx
  frontend/src/types/userType.ts
Labels: 🌝 FE, etc

#165 axios 모듈을 찾지 못하는 jest 오류
  frontend/package.json
  frontend/src/tests/App.test.tsx
Labels: bug, 🌝 FE

#169 프로필 페이지에 친구 추가 버튼 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#158 나의 프로필 수정을 하는 REST API 구현
  backend/.pnp.cjs
  backend/.yarn/cache/@types-validator-npm-13.7.14-4ec2b734b2-51bd82cd08.zip
  backend/.yarn/cache/class-transformer-npm-0.5.1-96b5161e6c-f191c8b4cc.zip
  backend/.yarn/cache/class-validator-npm-0.14.0-b600d5fe72-f62e4a0ad2.zip
  backend/.yarn/cache/libphonenumber-js-npm-1.10.24-9927ce085f-a79d98d398.zip
  backend/.yarn/cache/validator-npm-13.9.0-54b07e9e81-e2c936f041.zip
  backend/package.json
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/dtos/jwtPayload.dto.ts
  backend/src/api/my/dtos/my.dto.ts
  backend/src/api/my/dtos/setting.dto.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.module.ts
  backend/src/api/my/my.service.ts
  backend/src/guards/authenticated.guard.ts
  backend/src/main.ts
  backend/yarn.lock
Labels: feature, 🌚 BE

#166 자신의 프로필을 수정할 수 있는 프로필 수정 페이지 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/SettingProfilePage.tsx
Labels: feature, 🌝 FE

#170 팔로잉 목록 페이지 구현 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/Profile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Following.test.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#176 ProfileImage 컴포넌트가 userId를 받아오도록 수정
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/molecule/MessageList.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/Profile.tsx
  frontend/src/components/organisms/SearchResult/SearchResultItem.tsx
Labels: 🌝 FE, etc

#177 프로필 페이지에 차단 해제 버튼 추가
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#168 팔로잉 목록을 요청하는 REST API 구현
  backend/Dockerfile
  backend/src/api/auth/auth.service.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.module.ts
  backend/src/api/my/my.service.ts
  backend/src/app.module.ts
  docker-compose-dev.yml
Labels: feature, 🌚 BE

#178 최초 로그인하는 회원에게 보이는 온보딩 플로우 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/OnBoarding/MultiSteps.tsx
  frontend/src/components/organisms/OnBoarding/StepProfileImage.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/OnBoardingPage.tsx
  frontend/src/pages/SettingProfilePage.tsx
  frontend/src/tests/OnBoarding.test.tsx
  frontend/src/types/profileFormType.ts
Labels: feature, 🌝 FE

#185 Update Dockerfile
  backend/Dockerfile
Labels: 🌚 BE

#180 팔로우를 추가하는 REST API 구현
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
  backend/yarn.lock
Labels: feature, 🌚 BE

#184 API 응답 status code 수정
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/users/users.service.ts
Labels: bug, 🌚 BE

#179 2FA 설정 페이지에 2FA 설정 및 해제 버튼 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Setting2FAPage.tsx
Labels: feature, 🌝 FE

#193 following 요청, 추가 API 수정
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
Labels: bug, 🌚 BE

#186 팔로우를 삭제하는 REST API 구현
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
Labels: feature, 🌚 BE

#182 로그아웃 버튼 클릭 시 로그아웃 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/HeaderGnb.tsx
Labels: feature, 🌝 FE

#194 회원의 현재 상태를 확인할 수 있는 프로필 사진 옆 아이콘 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/MessageList.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/tests/Following.test.tsx
  frontend/src/types/userType.ts
Labels: feature, 🌝 FE

#187 차단 목록 요청, 추가, 삭제 API 구현
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
Labels: feature, 🌚 BE

#196 회원 검색하는 REST API 구현
  backend/src/api/users/dtos/users.dto.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.service.ts
Labels: feature, 🌚 BE

#189 최초 로그인 시 온보딩 페이지로 이동
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/OnBoarding/MultiSteps.tsx
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/hooks/useStore.ts
  frontend/src/pages/OnBoardingPage.tsx
  frontend/src/pages/SettingProfilePage.tsx
  frontend/src/tests/App.test.tsx
Labels: feature, 🌝 FE

#195 회원 검색 결과가 표시되는 회원 목록 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/SearchBar.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/SearchResultPage.tsx
Labels: feature, 🌝 FE

#198 프로필 페이지에 DM 버튼 추가
  frontend/src/components/organisms/Profile.tsx
Labels: feature, 🌝 FE

#205 endpoint 오타 수정
  backend/src/api/my/my.controller.ts
Labels: bug, 🌚 BE

#201 요청시마다 JWT 재생성
  backend/src/api/auth/auth.service.ts
  backend/src/guards/authenticated.guard.ts
Labels: feature, 🌚 BE

#207 프로필 이미지 요청 API 관련 이슈
  .gitignore
  backend/src/api/my/my.controller.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.service.ts
  backend/src/const.ts
  docker-compose-dev.yml
Labels: bug, 🌚 BE

#204 회원 관련 mock API 삭제
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile.tsx
  frontend/src/components/organisms/SearchResult/SearchResultItem.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#212 프로필 이미지 400 이슈
  backend/src/api/my/my.controller.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.service.ts
Labels: bug, 🌚 BE

#214 로그인, 온보딩 라우터 관련 무한 리다이렉션 오류
  frontend/src/components/molecule/HeaderGnb.tsx
Labels: bug, 🌝 FE

#215 401 오류를 받으면 로그인 페이지로 리다이렉트
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
Labels: feature, 🌝 FE

#217 User REST API & Swagger 정리
  backend/src/api/auth/auth.controller.ts
  backend/src/api/base.document.ts
  backend/src/api/my/dtos/my.dto.ts
  backend/src/api/my/dtos/setting.dto.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/users/dtos/users.dto.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.service.ts
  backend/src/app.controller.ts
Labels: bug, documentation, 🌚 BE

#223 채널 초대 기능 구현
  frontend/src/assets/styles/ChannelInvite.module.css
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/ChannelUserList.tsx
  frontend/src/components/molecule/TextInputWithDataList.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/components/organisms/ChannelInvite.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/tests/ChannelDetail.test.tsx
Labels: feature, 🌝 FE

#224 protected 방 입장 시 비밀번호 입력 기능 구현
  frontend/src/components/molecule/HeaderWithBackButton.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/components/organisms/ChannelPassword.tsx
  frontend/src/components/organisms/ChannelSetting/index.tsx
  frontend/src/pages/ChannelPage.tsx
Labels: feature, 🌝 FE

#226 Channel 관련 소켓 구현
  backend/.pnp.cjs
  backend/.yarn/cache/@nestjs-platform-socket.io-npm-9.3.12-220beb5627-45a20a7dcf.zip
  backend/.yarn/cache/@nestjs-websockets-npm-9.3.12-d0eecdfbe1-734c5ef2d2.zip
  backend/.yarn/cache/@socket.io-component-emitter-npm-3.1.0-3f778351c2-db069d9542.zip
  backend/.yarn/cache/@types-cookie-npm-0.4.1-274a704dc6-3275534ed6.zip
  backend/.yarn/cache/@types-cors-npm-2.8.13-4b8ac1068f-7ef197ea19.zip
  backend/.yarn/cache/@types-node-npm-18.15.11-fd8ceaaffd-977b4ad047.zip
  backend/.yarn/cache/base64id-npm-2.0.0-ef4afeee0a-581b1d37e6.zip
  backend/.yarn/cache/engine.io-npm-6.4.1-7939647717-b3921c3591.zip
  backend/.yarn/cache/engine.io-parser-npm-5.0.6-6021cc2c82-e92255b546.zip
  backend/.yarn/cache/object-hash-npm-3.0.0-d941e0cabe-80b4904bb3.zip
  backend/.yarn/cache/socket.io-adapter-npm-2.5.2-3456682203-481251c354.zip
  backend/.yarn/cache/socket.io-npm-4.6.1-7788788bd0-4479417271.zip
  backend/.yarn/cache/socket.io-parser-npm-4.2.2-22f4e4a017-ba929645cb.zip
  backend/.yarn/cache/ws-npm-8.11.0-ab72116a01-316b33aba3.zip
  backend/package.json
  backend/src/api/auth/auth.service.ts
  backend/src/api/channels/channels.controller.ts
  backend/src/api/channels/channels.gateway.ts
  backend/src/api/channels/channels.module.ts
  backend/src/api/channels/channels.service.ts
  backend/src/api/my/my.service.ts
  backend/src/app.module.ts
  backend/src/guards/authenticated.guard.ts
  backend/yarn.lock
Labels: feature, 🌚 BE

#231 소켓 설정
  frontend/.pnp.cjs
  frontend/.yarn/cache/@socket.io-component-emitter-npm-3.1.0-3f778351c2-db069d9542.zip
  frontend/.yarn/cache/@types-cors-npm-2.8.13-4b8ac1068f-7ef197ea19.zip
  frontend/.yarn/cache/@types-node-npm-18.15.11-fd8ceaaffd-977b4ad047.zip
  frontend/.yarn/cache/@types-socket.io-npm-3.0.2-745ac428ad-168cf77e48.zip
  frontend/.yarn/cache/base64id-npm-2.0.0-ef4afeee0a-581b1d37e6.zip
  frontend/.yarn/cache/cors-npm-2.8.5-c9935a2d12-ced838404c.zip
  frontend/.yarn/cache/engine.io-client-npm-6.4.0-614bfea593-f412a5d490.zip
  frontend/.yarn/cache/engine.io-npm-6.4.1-7939647717-b3921c3591.zip
  frontend/.yarn/cache/engine.io-parser-npm-5.0.6-6021cc2c82-e92255b546.zip
  frontend/.yarn/cache/socket.io-adapter-npm-2.5.2-3456682203-481251c354.zip
  frontend/.yarn/cache/socket.io-client-npm-4.6.1-fbfbf6a1e5-cc6abd3f9d.zip
  frontend/.yarn/cache/socket.io-npm-4.6.1-7788788bd0-4479417271.zip
  frontend/.yarn/cache/socket.io-parser-npm-4.2.2-22f4e4a017-ba929645cb.zip
  frontend/.yarn/cache/ws-npm-8.11.0-ab72116a01-316b33aba3.zip
  frontend/.yarn/cache/xmlhttprequest-ssl-npm-2.0.0-a9c0d5efed-1e98df67f0.zip
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/contexts/socket.ts
  frontend/yarn.lock
  nginx/proxy.conf
Labels: 🌝 FE, etc

#225 Tailwind CSS 적용
  frontend/.pnp.cjs
  frontend/.prettierrc.json
  frontend/.yarn/cache/@headlessui-react-npm-1.7.13-538d171a24-132e5fce86.zip
  frontend/.yarn/cache/@heroicons-react-npm-2.0.16-ce9dfa3c94-1e51bfec72.zip
  frontend/.yarn/cache/@tailwindcss-forms-npm-0.5.3-4d75c0dfda-9eddb4dbd0.zip
  frontend/.yarn/cache/@tailwindcss-typography-npm-0.5.9-c16859b9da-b98e21bdd1.zip
  frontend/.yarn/cache/client-only-npm-0.0.1-07d3e9505c-0c16bf660d.zip
  frontend/.yarn/cache/lodash.castarray-npm-4.4.0-f3706198e9-fca8c7047e.zip
  frontend/.yarn/cache/lodash.isplainobject-npm-4.0.6-d73937742f-29c6351f28.zip
  frontend/.yarn/cache/mini-svg-data-uri-npm-1.4.4-929f6f1119-997f1fbd8d.zip
  frontend/.yarn/cache/postcss-selector-parser-npm-6.0.10-a4d7aaa270-46afaa60e3.zip
  frontend/package.json
  frontend/prettier.config.js
  frontend/src/assets/styles/index.css
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/atoms/Label.tsx
  frontend/src/components/atoms/Message.tsx
  frontend/src/components/atoms/PageTitle.tsx
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/FileInputWithImage.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/HeaderWithBackButton.tsx
  frontend/src/components/molecule/SearchBar.tsx
  frontend/src/components/molecule/TextInputWithMessage.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/components/templates/AppTemplate.tsx
  frontend/src/components/templates/AppTemplateWithoutHeader.tsx
  frontend/src/index.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/pages/SettingProfilePage.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: feature, 🌝 FE

#247 채널 생성 페이지 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/ChannelNew.tsx
  frontend/src/contexts/socket.ts
Labels: feature, 🌝 FE
