Repository team-noir/the-pong, pull requests merged in 2023-04, with the labels that each got.

#255 채널 목록 페이지 구현 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/assets/styles/ChannelLobby.module.css
  frontend/src/components/atoms/PasswordInput.tsx
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelList.tsx
  frontend/src/components/molecule/PasswordModal.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/components/organisms/ChannelPassword.tsx
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/tests/ChannelBrowse.test.tsx
  frontend/src/tests/ChannelLobby.test.tsx
  frontend/src/types/channelType.ts
Labels: feature, 🌝 FE

#257 프로필 페이지에 DM 버튼 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/tests/Profile.test.tsx
Labels: feature, 🌝 FE

#260 개별 채널 페이지에서 메시지 주고받기 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/ChannelUserList.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/molecule/MessageList.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/tests/Channel.test.tsx
  frontend/src/tests/ChannelDetail.test.tsx
  frontend/src/types/channelUserType.ts
  frontend/src/types/messageType.ts
  frontend/tailwind.config.js
Labels: feature, 🌝 FE

#258 개별 채널 페이지에서 채널 설정 기능 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/ChannelNew.tsx
  frontend/src/components/organisms/ChannelSetting/ChannelSettingPassword.tsx
  frontend/src/components/organisms/ChannelSetting/ChannelSettingTitle.tsx
  frontend/src/components/organisms/ChannelSetting/index.tsx
  frontend/src/pages/ChannelPage.tsx
Labels: feature, 🌝 FE

#266 개별 채널 페이지에서 채널 초대 기능 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/SearchCombobox.tsx
  frontend/src/components/molecule/TextInputWithDataList.tsx
  frontend/src/components/organisms/ChannelInvite.tsx
  frontend/src/pages/ChannelPage.tsx
Labels: feature, 🌝 FE

#267 개별 채널 페이지에서 채널 나가기 버튼 API 요청
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/tests/ChannelDetail.test.tsx
Labels: feature, 🌝 FE

#261 개별 채널 페이지에서 참가자 목록 관리 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/ChannelUserList.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/tests/ChannelBrowse.test.tsx
  frontend/src/tests/ChannelDetail.test.tsx
  frontend/src/tests/ChannelLobby.test.tsx
  frontend/src/types/channelUserType.ts
Labels: feature, 🌝 FE

#280 게임 페이지 구현
  frontend/.pnp.cjs
  frontend/.yarn/cache/@types-react-reconciler-npm-0.28.2-694fc46c5c-9720f76a33.zip
  frontend/.yarn/cache/its-fine-npm-1.1.0-88a9e0e05f-4b8cf42b43.zip
  frontend/.yarn/cache/konva-npm-8.4.3-7e0af9b66e-5fc805e2c5.zip
  frontend/.yarn/cache/react-konva-npm-18.2.5-9f418274a4-3dcd7ea1b8.zip
  frontend/.yarn/cache/react-reconciler-npm-0.29.0-57f1460fdd-730db9cf45.zip
  frontend/package.json
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/molecule/HeaderWithBackButton.tsx
  frontend/src/components/organisms/Game/Ball.tsx
  frontend/src/components/organisms/Game/Paddle.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/routes.tsx
  frontend/yarn.lock
Labels: feature, 🌝 FE

#286 프로필 페이지에 게임 히스토리 추가
  frontend/src/components/molecule/GameHistoryList.tsx
  frontend/src/components/organisms/GameHistory.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#284 채널관련 백엔드 수정사항
  Makefile
  backend/prisma/schema.prisma
  backend/run.sh
  backend/src/api/auth/auth.service.ts
  backend/src/api/channels/channels.controller.ts
  backend/src/api/channels/channels.module.ts
  backend/src/api/channels/channels.service.ts
  backend/src/api/channels/models/channel.model.ts
  backend/src/api/channels/models/message.model.ts
  backend/src/api/channels/models/user.model.ts
  backend/src/app.gateway.ts
  backend/src/guards/authenticated.guard.ts
  backend/src/main.ts
  docker-compose-dev.yml
Labels: bug, 🌚 BE

#293 게임 시작 버튼을 눌렀을 때 나오는 게임 대기 상태 구현
  frontend/src/api/api.v1.ts
  frontend/src/assets/style.css
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/GameInviteButton.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/GameButtons.tsx
  frontend/src/components/templates/Modal.tsx
  frontend/src/hooks/useGame.ts
Labels: feature, 🌝 FE

#294 게임에 초대 받은 사람에게 보이는 초대장 구현
  frontend/src/App.tsx
  frontend/src/components/molecule/GameInviteModal.tsx
Labels: feature, 🌝 FE

#297 socket API 채널 notice 관련 코드 추가
  backend/src/api/channels/channels.module.ts
  backend/src/api/channels/channels.service.ts
  backend/src/api/channels/models/message.model.ts
  backend/src/api/channels/models/user.model.ts
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/const.ts
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/GameHistoryList.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/molecule/MessageList.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/components/organisms/ChannelInvite.tsx
  frontend/src/components/organisms/ChannelSetting/index.tsx
  frontend/src/components/organisms/ErrorFallbackWithHeader.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/ChannelPage.tsx
  frontend/src/types/index.ts
  frontend/src/utils/index.ts
Labels: feature, 🌚 BE, 🌝 FE, refactoring

#306 socket API 채널 notice 관련 코드 추가 - 리뷰 수정 반영
  frontend/src/components/organisms/Channel.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/ChannelPage.tsx
Labels: bug, 🌝 FE

#305 게임 결과 모달 구현, 게임 업적 모달 구현
  frontend/src/assets/style.css
  frontend/src/components/molecule/AchievementModal.tsx
  frontend/src/components/molecule/GameHistoryList.tsx
  frontend/src/components/organisms/Achievements/index.tsx
  frontend/src/components/templates/Modal.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#304 게임 옵션을 설정할 수 있는 페이지 구현
  frontend/src/App.tsx
  frontend/src/components/organisms/GameSetting.tsx
  frontend/src/components/templates/AppTemplate.tsx
  frontend/src/hooks/useGame.ts
  frontend/src/pages/GameSettingPage.tsx
  frontend/src/routes.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#308 프로필 수정 페이지에서 새로고침 후 닉네임 인풋이 비어있는 오류
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/components/templates/AppTemplate.tsx
Labels: bug, 🌝 FE

#311 닉네임 중복 검사 API
  backend/src/api/my/dtos/setting.dto.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
Labels: feature, 🌚 BE

#319 온보딩 완료 후 웰컴 컴포넌트를 페이지로 분리
  frontend/src/components/organisms/OnBoarding/MultiSteps.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/Welcome.tsx
  frontend/src/pages/OnBoardingPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/routes.tsx
Labels: feature, 🌝 FE

#317 온보딩, 프로필 수정 페이지에서 닉네임 중복검사 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/TextInputWithMessage.tsx
  frontend/src/components/organisms/OnBoarding/StepNickname.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/SettingProfile.tsx
Labels: feature, 🌝 FE

#322 익명 회원 로그인
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Login.tsx
Labels: feature, 🌝 FE

#328 JWT가 생성된 이후 소켓이 연결되도록 수정
  frontend/src/App.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/contexts/socket.ts
Labels: bug, feature

#315 2FA 설정을 위한 모달, 2FA OTP 코드를 입력받는 페이지 구현
  frontend/src/App.tsx
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/TextInput.tsx
  frontend/src/components/molecule/GameItem.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/HeaderWithBackButton.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/ChannelSetting/ChannelSettingTitle.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/components/organisms/Verify2FA.tsx
  frontend/src/hooks/useStore.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/GameLobbyPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/Root.tsx
  frontend/src/pages/SearchResultPage.tsx
  frontend/src/pages/Setting2FAPage.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/pages/Verify2FAPage.tsx
  frontend/src/routes.tsx
  frontend/src/tests/App.test.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#346 파일 경로 정리
  backend/package.json
  backend/src/api/auth/auth.controller.ts
  backend/src/api/auth/auth.module.ts
  backend/src/api/auth/auth.service.ts
  backend/src/api/auth/ft.strategy.ts
  backend/src/api/channels/channels.controller.ts
  backend/src/api/channels/channels.module.ts
  backend/src/api/channels/channels.service.spec.ts
  backend/src/api/channels/channels.service.ts
  backend/src/api/channels/dm.controller.ts
  backend/src/api/channels/models/channel.model.ts
  backend/src/api/channels/models/message.model.ts
  backend/src/api/channels/models/user.model.ts
  backend/src/api/games/games.controller.ts
  backend/src/api/games/games.module.ts
  backend/src/api/games/games.service.spec.ts
  backend/src/api/games/models/game.model.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.module.ts
  backend/src/api/my/my.service.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.module.ts
  backend/src/api/users/users.service.ts
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/guards/authenticated.guard.ts
  backend/src/prisma/prisma.service.ts
  backend/test/jest-e2e.json
  backend/tsconfig.json
Labels: 🌚 BE, refactoring

#347 게임 모드를 변경하는 API 구현
  backend/src/api/games/dtos/game.dto.ts
  backend/src/api/games/dtos/games.dto.ts
  backend/src/api/games/dtos/player.dto.ts
  backend/src/api/games/games.controller.ts
  backend/src/api/games/games.service.ts
  backend/src/api/games/models/game.model.ts
  backend/src/const.ts
Labels: feature, 🌚 BE

#342 게임 대기 취소, 초대 취소, 초대 응답 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/GameInviteButton.tsx
  frontend/src/components/molecule/GameInviteModal.tsx
  frontend/src/components/organisms/GameButtons.tsx
  frontend/src/hooks/useGame.ts
Labels: feature, 🌝 FE

#343 로그아웃 시 소켓 연결 끊기
  frontend/src/components/molecule/HeaderGnb.tsx
Labels: bug, 🌝 FE

#345 회원 검색을 페이지로 분리
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/components/molecule/UserList.tsx
  frontend/src/components/organisms/Search.tsx
  frontend/src/components/organisms/SearchResult/SearchResultItem.tsx
  frontend/src/components/organisms/SearchResult/SearchResultList.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/pages/SearchPage.tsx
  frontend/src/pages/SearchResultPage.tsx
  frontend/src/routes.tsx
Labels: 🌝 FE, refactoring

#349 프로필 페이지 mutation 정리
  frontend/src/components/molecule/GameHistoryList.tsx
  frontend/src/components/organisms/Achievements/index.tsx
  frontend/src/components/organisms/GameHistory.tsx
  frontend/src/components/organisms/Profile.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: 🌝 FE, refactoring

#351 채널 초대 관련 에러
  backend/src/api/games/dtos/player.dto.ts
  backend/src/api/games/games.service.spec.ts
  backend/src/api/games/games.service.ts
  backend/src/api/games/models/game.model.ts
  backend/src/app.gateway.ts
Labels: bug, 🌚 BE

#353 채널 버튼 노출 오류 수정, 쿼리 refetchInterval 기본 설정 삭제
  frontend/src/App.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/organisms/Channel.tsx
  frontend/src/components/organisms/ChannelDetail.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/contexts/socket.ts
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/pages/Root.tsx
Labels: bug, 🌝 FE, refactoring

#359 업적 목록을 요청하는 REST API 구현
  .gitignore
  backend/.dockerignore
  backend/Dockerfile
  backend/package.json
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/run.sh
  backend/src/api/users/dtos/achievement.dto.ts
  backend/src/api/users/users.controller.ts
  backend/src/api/users/users.service.ts
  backend/tsconfig.build.json
  backend/tsconfig.json
  frontend/Dockerfile
  frontend/Dockerfile.dev
Labels: feature, 🌚 BE

#362 프로필 페이지에서 업적 목록 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/AchievementModal.tsx
  frontend/src/components/organisms/Achievements/AchievementItem.tsx
  frontend/src/components/organisms/Achievements/AchievementList.tsx
  frontend/src/components/organisms/Achievements/index.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#363 회원 & 채널 API 수정 사항
  backend/prisma/schema.prisma
  backend/src/api/channels/channels.controller.ts
  backend/src/api/games/models/game.model.ts
  backend/src/api/my/dtos/my.dto.ts
  backend/src/api/my/my.service.ts
  backend/src/api/users/dtos/users.dto.ts
  backend/src/api/users/users.service.ts
  frontend/src/api/api.v1.ts
  frontend/src/hooks/useStore.ts
  frontend/src/types/index.ts
Labels: 🌚 BE, 🌝 FE, refactoring

#366 Prisma studio 설정
  README.md
  backend/package.json
  backend/run.sh
  docker-compose-dev.yml
Labels: feature, 🌚 BE

#364 게임 준비 완료하는 WebRTC 구현
  .gitignore
  backend/.dockerignore
  backend/prisma/schema.prisma
  backend/prisma/yarn.lock
  backend/src/api/channels/models/channel.model.ts
  backend/src/api/games/dtos/game.dto.ts
  backend/src/api/games/dtos/games.dto.ts
  backend/src/api/games/dtos/player.dto.ts
  backend/src/api/games/games.controller.ts
  backend/src/api/games/games.module.ts
  backend/src/api/games/games.service.spec.ts
  backend/src/api/games/games.service.ts
  backend/src/api/games/models/game.model.ts
  backend/src/api/users/users.service.ts
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/const.ts
Labels: feature, 🌚 BE

#370 프로필 페이지에 레벨 추가
  frontend/src/components/organisms/Profile.tsx
Labels: feature, 🌝 FE

#371 프로필 설정 페이지에 디폴트 이미지가 뜨지 않는 문제
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/FileInputWithImage.tsx
  frontend/src/constants/index.ts
Labels: bug, 🌝 FE

#367 게임 페이지 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/molecule/GameScoretable.tsx
  frontend/src/components/organisms/Game/GameResultModal.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/components/organisms/GameButtons.tsx
  frontend/src/components/organisms/GameLives.tsx
  frontend/src/hooks/useGamePlay.ts
  frontend/src/hooks/useGameRTC.ts
  frontend/src/pages/GamePage.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#387 React 배포용 multi-stage 설정 - 2
  frontend/Dockerfile
  frontend/src/constants/index.ts
  nginx/Dockerfile
  nginx/Dockerfile.dev
Labels: etc

#377 RTC 연결 시 소켓 아이디가 아니라 회원 아이디 사용
  frontend/src/hooks/useGameRTC.ts
Labels: bug, 🌝 FE

#381 팔로잉 페이지의 메시지 보내기 버튼 API 호출
  frontend/src/components/organisms/Following.tsx
  frontend/src/pages/FollowingPage.tsx
Labels: feature, 🌝 FE

#383 게임 설정, 게임 페이지의 나가기 버튼 삭제
  frontend/src/components/molecule/Header.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/GameSettingPage.tsx
Labels: feature, 🌝 FE

#390 게임 플레이 중 발생되는 문제
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useGamePlay.ts
  frontend/src/hooks/useGameRTC.ts
  frontend/src/types/index.ts
Labels: bug, feature, 🌝 FE

#400 도커와 VM 관련 설정
  Makefile
  README.md
  backend/Dockerfile
  docker-compose-dev.yml
  docker-compose.yml
Labels: bug, etc

#392 메인 페이지, 게임 로비의 라이브 게임 목록 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/molecule/GameItem.tsx
  frontend/src/components/molecule/GameList.tsx
  frontend/src/components/organisms/GameLives.tsx
  frontend/src/pages/GameLobbyPage.tsx
  frontend/src/pages/MainPage.tsx
Labels: feature, 🌝 FE

#402 게임 종료 시에도 점수를 업데이트하도록 수정
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/hooks/useGamePlay.ts
Labels: bug, 🌝 FE

#407 게임 라이브 참가 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/GameLives.tsx
Labels: feature, 🌝 FE

#410 게임 배경 이미지 소스 추가
  frontend/public/images/bg_backstreet.jpg
  frontend/public/images/bg_pier.jpg
  frontend/public/images/bg_storage.jpg
  frontend/src/constants/index.ts
Labels: feature, 🌝 FE
