Repository team-noir/the-pong, pull requests merged in 2023-05, with the labels that each got.

#411 라우트 에러 페이지에 메인으로 가기 버튼 추가
  frontend/src/components/organisms/ErrorFallback.tsx
  frontend/src/components/organisms/ErrorFallbackWithHeader.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/Verify2FAPage.tsx
Labels: feature, 🌝 FE

#416 게임 모드, 테마 구현
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Game/Ball.tsx
  frontend/src/components/organisms/Game/Paddle.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/components/organisms/GameSetting.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useGamePlay.ts
  frontend/src/pages/GameSettingPage.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#417 게임 플레이 페이지에서 뒤로가는 경우, 메인 페이지로 이동
  frontend/src/pages/GameSettingPage.tsx
Labels: bug, 🌝 FE

#418 종료된 게임을 관전하려는 경우, 알림과 함께 리렌더링
  frontend/src/components/organisms/GameLives.tsx
Labels: bug, 🌝 FE

#419 게임 결과에서 기권한 플레이어를 표시
  frontend/src/components/organisms/Game/GameResultModal.tsx
  frontend/src/types/index.ts
Labels: feature, 🌝 FE

#427 onClickClose 핸들러가 없는 모달의 닫기 버튼 숨기기
  frontend/src/components/molecule/GameInviteButton.tsx
  frontend/src/components/molecule/GameInviteModal.tsx
  frontend/src/components/organisms/GameButtons.tsx
Labels: bug, 🌝 FE

#429 queryKey를 상수로 관리하기
  frontend/src/App.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/GameLives.tsx
  frontend/src/components/organisms/GameLobby.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/components/organisms/Main.tsx
  frontend/src/components/organisms/Profile/Achievements.tsx
  frontend/src/components/organisms/Profile/index.tsx
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/components/organisms/Welcome.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/GameSettingPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/SettingBlocksPage.tsx
Labels: 🌝 FE, etc

#425 프로필 페이지의 게임 히스토리 목록 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/organisms/Profile/GameHistory.tsx
Labels: feature, 🌝 FE

#437 게임 결과 창에서 점수가 적용되지 않는 문제
  backend/src/api/games/models/game.model.ts
Labels: bug, 🌚 BE

#431 REST API 응답 수정
  backend/src/api/auth/auth.controller.ts
  backend/src/api/channels/channels.controller.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/users/users.controller.ts
  frontend/.pnp.cjs
  frontend/.yarn/cache/http-status-codes-npm-2.2.0-8d45a60399-31e1d73085.zip
  frontend/package.json
  frontend/src/api/api.v1.ts
  frontend/yarn.lock
Labels: 🌚 BE, 🌝 FE, etc

#445 health-check의 응답이 502인 상황에서 빈 화면
  frontend/src/components/organisms/ErrorFallbackWithHeader.tsx
Labels: bug, 🌝 FE

#440 회원의 현재 상태를 조회하는 API 호출
  frontend/src/api/api.v1.ts
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/GameInviteModal.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/molecule/ProfileImageWithStatus.tsx
  frontend/src/components/molecule/UserItem.tsx
  frontend/src/constants/queryKeys.ts
Labels: feature, 🌝 FE

#448 socket 관련 메소드를 별도의 파일로 구분
  frontend/src/App.tsx
  frontend/src/api/rest.v1.ts
  frontend/src/api/socket.v1.ts
  frontend/src/components/atoms/ProfileImage.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/GameInviteButton.tsx
  frontend/src/components/molecule/GameInviteModal.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/organisms/Channel/ChannelDetail.tsx
  frontend/src/components/organisms/Channel/ChannelInvite.tsx
  frontend/src/components/organisms/Channel/ChannelSetting/index.tsx
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
  frontend/src/components/organisms/ChannelNew.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/components/organisms/GameButtons.tsx
  frontend/src/components/organisms/GameLives.tsx
  frontend/src/components/organisms/GameLobby.tsx
  frontend/src/components/organisms/GameSetting.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/components/organisms/Main.tsx
  frontend/src/components/organisms/OnBoarding/StepNickname.tsx
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/Profile/Achievements.tsx
  frontend/src/components/organisms/Profile/GameHistory.tsx
  frontend/src/components/organisms/Profile/index.tsx
  frontend/src/components/organisms/Search.tsx
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/components/organisms/Verify2FA.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/socketEvents.ts
  frontend/src/contexts/socket.ts
  frontend/src/hooks/useGame.ts
  frontend/src/hooks/useGamePlay.ts
  frontend/src/hooks/useGameRTC.ts
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/ChannelPage.tsx
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/GamePage.tsx
  frontend/src/pages/GameSettingPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/SettingBlocksPage.tsx
Labels: 🌝 FE, etc

#444 프로필 수정이 되지 않는 문제
  frontend/src/api/rest.v1.ts
  frontend/src/components/organisms/SettingProfile.tsx
  frontend/src/utils/validatorUtils.ts
Labels: bug, 🌝 FE

#447 프로필 사진을 삭제하는 REST API 구현
  backend/run.sh
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
Labels: feature, 🌚 BE

#458 현재 채널에 해당하는 소켓 메시지만 받도록 수정
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/types/index.ts
Labels: bug, 🌝 FE

#462 채널 소켓 이벤트 핸들링
  frontend/src/components/molecule/ProfileImageWithStatus.tsx
  frontend/src/components/organisms/Channel/ChannelDetail.tsx
  frontend/src/components/organisms/Channel/index.tsx
Labels: feature, 🌝 FE

#466 채널 관련 수정 사항
  frontend/src/App.tsx
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelUserList.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
Labels: bug, feature, 🌝 FE

#474 채널 초대 회원 검색 API 호출 시 디바운스
  frontend/src/components/organisms/Channel/ChannelInvite.tsx
  frontend/src/hooks/useDebounce.ts
Labels: feature, 🌝 FE

#479 채널 아이콘 표시
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
Labels: feature, 🌝 FE

#487 업적 관련 오타 수정
  frontend/src/api/socket.v1.ts
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/constants/socketEvents.ts
Labels: bug, 🌝 FE

#488 게임 히스토리 목록에 승급전 표시
  frontend/src/components/molecule/GameHistoryList.tsx
Labels: feature, 🌝 FE

#468 서버 이미지 파일 유효성 검사
  backend/src/api/my/my.controller.ts
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/SettingProfile.tsx
Labels: feature, 🌚 BE, 🌝 FE

#493 게임 페이지에서 뒤로 가기를 했을 때 게임 설정 페이지로 가지 않도록 수정
  frontend/src/components/organisms/GameSetting.tsx
Labels: bug, 🌝 FE

#495 채널 설정 리팩토링
  frontend/src/components/organisms/GameSetting.tsx
Labels: 🌝 FE, etc

#497 관전자가 게임방을 나와도 ping 이벤트를 리스닝하는 문제
  frontend/src/hooks/useGamePlay.ts
Labels: bug, 🌝 FE

#478 스타일링
  frontend/src/assets/style.css
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/molecule/ChannelUserItem.tsx
  frontend/src/components/molecule/GameMatchtable.tsx
  frontend/src/components/molecule/GameScoretable.tsx
  frontend/src/components/molecule/Header.tsx
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/components/organisms/ErrorFallback.tsx
  frontend/src/components/organisms/ErrorFallbackWithHeader.tsx
  frontend/src/components/organisms/Game/GameResultModal.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/components/organisms/Profile/Achievements.tsx
  frontend/src/components/organisms/Setting2FA.tsx
  frontend/src/components/templates/AppTemplate.tsx
  frontend/src/pages/ErrorPage.tsx
Labels: 🌝 FE, etc

#503 로딩 스피너 추가
  frontend/src/App.tsx
  frontend/src/components/atoms/Spinner.tsx
  frontend/src/components/organisms/LoadingFallback.tsx
  frontend/src/components/organisms/Login.tsx
  frontend/src/components/templates/AppTemplate.tsx
  frontend/src/components/templates/AppTemplateWithoutHeader.tsx
Labels: feature, 🌝 FE

#506 manifest와 파비콘 수정
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/src/components/organisms/ErrorFallback.tsx
  frontend/src/components/organisms/Login.tsx
Labels: feature, 🌝 FE

#507 로그인 시도시 unhandled error
  backend/src/api/channels/channels.service.ts
  backend/src/api/my/my.controller.ts
  backend/src/api/my/my.service.ts
  backend/src/app.gateway.ts
Labels: bug, 🌚 BE

#508 참가 중인 게임 충돌 제거
  backend/src/api/games/dtos/game.dto.ts
  backend/src/api/games/games.service.ts
  backend/src/api/games/models/game.model.ts
Labels: bug, 🌚 BE

#515 프로필 이미지 사이즈 오류
  backend/src/api/my/my.controller.ts
  backend/src/const.ts
Labels: bug, 🌚 BE

#512 .env.example 수정
  .env.development.example
  .env.example
  Makefile
Labels: etc

#517 초기에 로그인 화면이 깜빡이는 문제
  frontend/src/App.tsx
Labels: bug, 🌝 FE

#526 게임 초대한 사람이 게임 설정 화면을 거치지 않는 오류
  frontend/src/components/molecule/GameInviteButton.tsx
Labels: bug, 🌝 FE

#528 비밀번호가 없는 채널을 생성할 때도 유효성 검사를 하는 문제
  frontend/src/components/organisms/ChannelNew.tsx
  frontend/src/types/index.ts
Labels: bug, 🌝 FE

#533 게임 화면에서 버튼 하단 배경이 잘리는 문제
  frontend/src/components/organisms/Game/index.tsx
Labels: 🌝 FE, etc

#537 '로그인 없이 둘러보기' 텍스트 변경
  frontend/src/components/organisms/Login.tsx
Labels: 🌝 FE, etc

#538 게임 초대 관련 리터럴 문자열을 상수로 관리
  frontend/src/components/molecule/GameInviteButton.tsx
  frontend/src/constants/index.ts
Labels: 🌝 FE, refactoring

#542 비밀번호가 있는 방에서 내보내기되는 경우 400 에러를 받는 문제
  frontend/src/components/organisms/Channel/index.tsx
Labels: bug, 🌝 FE

#554 닉네임 중복 검사 디바운스
  frontend/src/components/organisms/OnBoarding/index.tsx
  frontend/src/components/organisms/SettingProfile.tsx
Labels: feature, 🌝 FE

#555 모바일 환경에서 작동할 수 있도록 게임 버튼 이벤트 수정
  frontend/src/components/atoms/Button.tsx
  frontend/src/components/organisms/Game/index.tsx
  frontend/src/hooks/useGamePlay.ts
Labels: bug, 🌝 FE

#563 ChannelListDto 수정
  backend/src/api/channels/dtos/channel.dto.ts
Labels: bug, 🌚 BE

#569 리스트를 요청하는 API에 대한 페이지네이션 추가
  frontend/.pnp.cjs
  frontend/.yarn/cache/react-infinite-scroll-component-npm-6.1.0-fc628f1f18-3708398934.zip
  frontend/.yarn/cache/throttle-debounce-npm-2.3.0-0e354dff02-6d90aa2ddb.zip
  frontend/package.json
  frontend/src/api/rest.v1.ts
  frontend/src/components/molecule/ChannelItem.tsx
  frontend/src/components/molecule/ChannelList.tsx
  frontend/src/components/molecule/MessageItem.tsx
  frontend/src/components/molecule/MessageList.tsx
  frontend/src/components/molecule/ProfileImageWithStatus.tsx
  frontend/src/components/organisms/Channel/ChannelInvite.tsx
  frontend/src/components/organisms/Channel/index.tsx
  frontend/src/components/organisms/ChannelBrowse.tsx
  frontend/src/components/organisms/ChannelLobby.tsx
  frontend/src/components/organisms/Following.tsx
  frontend/src/components/organisms/GameList.tsx
  frontend/src/components/organisms/GameLobby.tsx
  frontend/src/components/organisms/Main.tsx
  frontend/src/components/organisms/Profile/Achievements.tsx
  frontend/src/components/organisms/Profile/GameHistory.tsx
  frontend/src/components/organisms/Search.tsx
  frontend/src/components/organisms/SettingBlocks.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/ChannelBrowsePage.tsx
  frontend/src/pages/ChannelLobbyPage.tsx
  frontend/src/pages/FollowingPage.tsx
  frontend/src/pages/SettingBlocksPage.tsx
  frontend/src/types/index.ts
  frontend/yarn.lock
Labels: feature, 🌝 FE, bonus

#578 42 로그인을 구글 로그인으로 수정
  frontend/src/api/rest.v1.ts
  frontend/src/assets/images/logo_42.svg
  frontend/src/assets/images/logo_google.svg
  frontend/src/components/organisms/Login.tsx
Labels: feature, 🌝 FE, bonus

#586 페이징 커서 타입 변경
  frontend/src/types/index.ts
Labels: 🌝 FE, etc

#584 aws에 배포하기 위한 도커 설정
  .env.example
  .gitignore
  Makefile
  docker-compose-aws.yml
  frontend/Dockerfile.aws
  frontend/package.json
  frontend/src/App.tsx
  nginx/Dockerfile.aws
  nginx/proxy-aws.conf
Labels: etc

#589 Github pages 배포용 액션 파일 지우기
  .github/workflows/frontend.yml
Labels: etc

#567 Styling
  frontend/src/assets/style.css
  frontend/src/components/molecule/HeaderGnb.tsx
  frontend/src/components/templates/Modal.tsx
Labels: feature, 🌝 FE
